spring:
  mongodb:
    uri: mongodb+srv://DbUser:India123@cluster1.bz3paly.mongodb.net
    database: TransactionOrders
  datasource:
    username: postgres
    password: India123
    url: jdbc:postgresql://localhost:5435/transactionorder 
